name: Weaver unit tests

on:
  push:
  workflow_dispatch:

jobs:
  test-weaver:
    runs-on: ubuntu-latest
    name: Run unit tests + mypy
    steps:
      - uses: SuffolkLITLab/ALActions/pythontests@main
